#!/bin/bash

head --bytes=5000000 /dev/urandom > output.txt
./tr2b "1234567890!@#$%^&*()_+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" "!@#$%^&*()_+0987654321ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz" < output.txt > test1.txt
./tr2u "1234567890!@#$%^&*()_+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" "!@#$%^&*()_+0987654321ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz" < output.txt > test2.txt
tr "1234567890!@#$%^&*()_+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" "!@#$%^&*()_+0987654321ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz" < output.txt > test3.txt
./g2 "1234567890!@#$%^&*()_+abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" "!@#$%^&*()_+0987654321ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz" < output.txt > test4.txt

diff test1.txt test2.txt
diff test2.txt test3.txt
diff test1.txt test3.txt
diff test1.txt test4.txt
diff test2.txt test4.txt
diff test3.txt test4.txt
